FROM openjdk:8-jdk-alpine as runner
VOLUME ["/tmp","/logs"]
ENV TZ=Asia/Shanghai
ENV ACTIVE=defualt
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ADD /target/cloud-basedata-service-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=${ACTIVE}","-jar","app.jar"]