server:
   port: 8081
spring:
   application:
      name: cloud-user-service
   profiles:
      active: test
   zipkin:
      baseUrl: http://localhost:8080
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/stockmarket?useUnicode=true&characterEncoding=utf8&&serverTimezone=GMT%2B8
      username: root
      password: Madan~1988
   jpa:
      hibernate:
         database-platform: org.hibernate.dialect.MySQLDialect
         ddl-auto: none
         show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG