pipeline {
agent any
  stages {
        stage('git clone') {
            steps {
                git credentialsId: 'a6149833-8684-4a32-b3f2-25c127ce5bf8', url: 'https://github.com/madandm/fullstack_milstone3.git'
            }
        }
        stage('Build') {
            steps {
                dir('./'){
                    bat 'mvn clean install -Dmaven.test.skip=true'
                }
            }
        }
       stage('deploy') {
            steps {
                // deploy by windows command
                sh 'ssh root@124.93.1.60'
                sh 'docker run -d -p 8080:8080 -v /home/data:/webapps --name search tomcat:9.0'
                sh 'echo deploy success'
            }
        }
   }
}